### PR TITLE
Add metadata for JACK

### LINKED ISSUE #225: Implement JACK metadata
Add a mechanism to manage JACK metadata on GNU/Linux.

### PR DESCRIPTION
**Pull request by nicolasdanet**
Fixes #225

**Proposed changes**
 
  - Add global messages to set/unset metadata for JACK on GNU/Linux (see below).
  - Note that it is not documented (it could change as everything here).
  - I can NOT tested it since it is a feature too recent for QjackCtl on Ubuntu 18.04 and Raspbian.
  - Seems too recent for Ubuntu 20.04 also!
  - For now Spaghettis is targeted on LTS system only.
  - I'm alone sadly and sadly i don't have the time to check all configs (such KXStudio stuff).
  - Thanks for feedback.

`[ ; pd metadata input 1 cv 1 (` 
`[ ; pd metadata input 1 minimum 0 (`
`[ ; pd metadata input 1 maximum 10 (`
`[ ; pd metadata output 2 name Foo (`
`[ ; pd metadata reset (`

### CODE REVIEW

**Comment by nicolasdanet** [comment]
I can add (improve) more metadata if somebody is able to fully test them!

**Comment by mxmilkb** [comment]
Carla [has had](https://github.com/falkTX/Carla/commits/develop) it's version bumped to 2.1-RC1 but not tagged/announced yet, it comes with more robust CV support and I've been trying to work through recreating [the LMP example](https://www.youtube.com/watch?v=eMj-q5adAZ4) though there a few wrinkles to iron out.

After that, I'd very much love to test Spaghettis for driving CV things.

I mentioned Spaghettis in #dataflow on Freenode, there was a bit of feedback;

```
...
<IOhannes> although i'd prefer the messages to be (more) stateless...
<IOhannes> e.g. why can you set the "minimum" value without the "maximum" value?
<IOhannes> what do those values mean if the port is not a CV port?
<IOhannes> how can I reset the metadata for the audio I/O *only*? (that is: "metadata" seems to be *quite* generic and probably should not be restricted to only JACK-metadata on the long run)
```

If you're on IRC, I'd recommend #lad on Freenode.

**Comment by mxmilkb** [comment]
I've added Spaghettis to the AUR: https://aur.archlinux.org/packages/spaghettis-git

**Comment by nicolasdanet** [comment]
The metadata settings are just labels. They currently doesn't clamp anything. Except that marking a port cv disable internal [-1 1] audio clipping. Probably that in the futur it would be possible to set minimum and maximum only if the port is cv. Anyway i think that only usage of that feature will help to improve the feature. That is the benefit of work-in-progress. Experiment and if it is bad, change it. Personnaly i have no opinion about for what metadata can is usefull! If anybody wnat to make it differently, just propose it.

**Comment by nicolasdanet** [comment]
At first i was thinking about something like below, but i doubt that the metadata label could be used in other situations. But as said above, i'm open to suggestions.

[ ; pd JACK metadata output 1 cv 1 (

**Comment by nicolasdanet** [comment]
Note that I quickly tested it with QjackCtl 0.6 on Manjaro and it seems OK.

**Pull request merged**
